FROM richardsmashington/cpp_unittest_style_grader:latest

LABEL author="Matthew Butner"
LABEL mainter="mfbutner@ucdavis.edu"

COPY requirements.txt /requirements.txt
RUN pip3 install --no-cache-dir -r /requirements.txt